name: Build for linux_riscv64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-linux_riscv64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          OS: "linux"
          ARCH: "riscv64"
          CROSS_COMPILE: "riscv64-linux-gnu"
          CROSS_COMPILE_PKG_SUFFIX: "riscv64-linux-gnu"
          PLATFORM: "linux"
