name: Build for linux_aarch64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-linux_aarch64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          OS: "linux"
          ARCH: "aarch64"
          CROSS_COMPILE: "aarch64-linux-gnu"
          CROSS_COMPILE_PKG_SUFFIX: "aarch64-linux-gnu"
          PLATFORM: "linux"
