name: Build for windows_i686

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows_i686:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg
        uses: ./.github/actions/build
        with:
          OS_NAME: "windows"
          ARCH: "i686"
          CROSS_COMPILE: "i686-w64-mingw32"
          CROSS_COMPILE_PKG_SUFFIX: "mingw-w64-i686"
          PLATFORM: "mingw32"
