name: Build for windows_x86_64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows_x86_64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg
        uses: ./.github/actions/build
        with:
          OS_NAME: "windows"
          ARCH: "x86_64"
          CROSS_COMPILE: "x86_64-w64-mingw32"
          CROSS_COMPILE_PKG_SUFFIX: "mingw-w64-x86-64"
          PLATFORM: "mingw32"
