name: Build for darwin_x86_64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-darwin_x86_64:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg
        uses: ./.github/actions/build
        with:
          OS_NAME: "darwin"
          ARCH: "x86_64"
