name: Build for darwin_aarch64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-darwin_aarch64:
    name: Build
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          OS: "darwin"
          ARCH: "aarch64"
