name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    name: Check for version increment
    uses: ./.github/workflows/check-version.yml

  build:
    name: Build packages
    uses: ./.github/workflows/build.yml
    needs: check-version
    if: ${{ needs.check-version.outputs.version_change == 'true' }}

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4

      - name: Gather artifacts
        run: |
          mkdir -pv dist
          mv dist-*/* dist/

      - name: Compress binaries
        run: |
          UPX_VERSION="5.0.1"
          wget -q https://github.com/upx/upx/releases/download/v$UPX_VERSION/upx-$UPX_VERSION-amd64_linux.tar.xz -O dl/upx.tar.xz
          tar -xf dl/upx.tar.xz -C bin/
          for FNAME in dist/*; do
            bin/upx-*/upx -q --best --ultra-brute "$FNAME" 1>/dev/null &
          done
          wait

      - name: Release to GitHub
        if: ${{ steps.check-version.outputs.version_change == 'true' }}
        uses: softprops/action-gh-release@v2.0.2
        with:
          token: ${{ secrets.GH_TOKEN_RELEASES }}
          files: |
            dist/*